"""empty message

Revision ID: 1d293f5ff15a
Revises: aee141540a78
Create Date: 2023-03-08 15:58:38.092954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d293f5ff15a'
down_revision = 'aee141540a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('unique_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('unique_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
