"""empty message

Revision ID: 2b8d305f71ff
Revises: 
Create Date: 2023-03-05 01:43:09.895046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8d305f71ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=45), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('pet_type', sa.String(length=300), nullable=False),
    sa.Column('pet_breed', sa.String(length=300), nullable=True),
    sa.Column('pet_weight', sa.Integer(), nullable=True),
    sa.Column('pet_gender', sa.String(length=45), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('pet_picture', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_table('user')
    # ### end Alembic commands ###
